# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=700']
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools==57.4.9]
        args: [--ignore-missing-imports]
