version: "3.8"

services:

  ckan-db:
    image: postgis/postgis:14-3.1
    environment:
      POSTGRES_USER: ckan-dev
      POSTGRES_PASSWORD: ckan-dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - target: 5432
        published: 55432
    networks:
      - default
      - tester

  datastore-db:
    image: postgis/postgis:14-3.1
    environment:
      POSTGRES_USER: datastore-dev
      POSTGRES_PASSWORD: datastore-dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - target: 5432
        published: 55433

  ckan-web:
    image: kartoza/ckanext-dalrrd-emc-dcpr:add-dockerfile
    volumes:
      - type: bind
        source: $PWD/..
        target: /home/appuser/app
      - type: bind
        source: $PWD/ckan-dev-settings.ini
        target: /home/appuser/ckan.ini
      - type: bind
        source: $PWD/who.ini
        target: /home/appuser/who.ini
      - ckan-storage:/home/appuser/data
    ports:
      - target: 5000
        published: 5000

  # NOTE: ckan/solr uses solr v 6.6 which is pretty old (EOL even), but as of CKAN 2.9.x it is
  # unfortunately still the most recent supported version. More info:
  # - https://github.com/ckan/ckan/issues/5585
  # - https://github.com/ckan/ckan/pull/5143
  solr:
    image: ckan/solr
    ports:
      - target: 8983
        published: 8983
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data
    networks:
      - default
      - tester

  redis:
    image: redis:6.2
    networks:
      - default
      - tester


volumes:
  solr-data:
  ckan-storage:


networks:
  tester:
    external: true