# NOTE: this file expects to find the $CKAN_IMAGE_TAG variable in its environment

version: "3.8"

services:

  ckan-web:
    image: kartoza/ckanext-dalrrd-emc-dcpr:${CKAN_IMAGE_TAG}

  ckan-harvesting-gatherer:
    image: kartoza/ckanext-dalrrd-emc-dcpr:${CKAN_IMAGE_TAG}
    command: ["launch-ckan-cli", "harvester", "gather-consumer"]

  ckan-harvesting-fetcher:
    image: kartoza/ckanext-dalrrd-emc-dcpr:${CKAN_IMAGE_TAG}
    command: ["launch-ckan-cli", "harvester", "fetch-consumer"]

  ckan-harvesting-runner:
    image: kartoza/ckanext-dalrrd-emc-dcpr:${CKAN_IMAGE_TAG}

  ckan-mail-sender:
    image: kartoza/ckanext-dalrrd-emc-dcpr:${CKAN_IMAGE_TAG}

  ckan-db:
    image: postgis/postgis:13-3.1
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  datastore-db:
    image: postgis/postgis:13-3.1
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      DATASTORE_READONLY_USER: datastore-default
      DATASTORE_READONLY_USER_PASSWORD: datastore-default
    volumes:
      - type: bind
        source: $PWD/datastore-db
        target: /docker-entrypoint-initdb.d

  # NOTE: ckan/solr uses solr v 6.6 which is pretty old (EOL even), but as of CKAN 2.9.x it is
  # unfortunately still the most recent supported version. More info:
  # - https://github.com/ckan/ckan/issues/5585
  # - https://github.com/ckan/ckan/pull/5143
  solr:
    image: ckan/solr
    volumes:
      - type: bind
        source: $PWD/solr/schema.xml
        target: /opt/solr/server/solr/ckan/conf/schema.xml

  redis:
    image: redis:6.2
