# NOTE: this file expects to find the $GIT_BRANCH_NAME variable in its environment
# under normal circumstances, this is run in the CI environment, and that variable
# has been made available by a previous step

version: "3.8"

services:

  ckan-web:
    image: kartoza/ckanext-dalrrd-emc-dcpr:${GIT_BRANCH_NAME}
    volumes:
      - type: bind
        source: $PWD/who.ini
        target: /home/appuser/who.ini
    ports:
      - target: 5000
        published: 5000

  ckan-db:
    environment:
      POSTGRES_USER: ckan-ci
      POSTGRES_PASSWORD: ckan-ci
      PGDATA: /var/lib/postgresql/data/pgdata
