name: EMC staging github workflow
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: EMC staging continous deployment
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Run common CI
        uses: ./.github/actions/action-common-ci
        with:
          image-name: kartoza/ckanext-dalrrd-emc-dcpr

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current git commit hash
        uses: priyesh2609/sha-trim-action@v1.1.1

      - name: Get current git branch name
        uses: EthanSK/git-branch-name-action@v1

      - name: publish image to dockerhub
        env:
          IMAGE_NAME: ${{ github.repository }}
        run: |
          docker push $IMAGE_NAME:${GIT_BRANCH_NAME}
          docker push $IMAGE_NAME:${TRIMMED_SHA}
